# fly --target spring-team login --team-name spring-team --concourse-url https://ci.spring.io
# fly --target spring-team set-pipeline --config pipeline.yml --pipeline spring-boot-thin-launcher --load-vars-from credentials.yml
---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/nebhale/slack-notification-resource

resources:
- name: source
  type: git
  source:
    uri: https://github.com/spring-projects-experimental/spring-boot-thin-launcher.git
- name: slack
  type: slack-notification
  source:
    url: {{slack-url}}
 
slack-failure: &slack-failure
  put: slack
  params:
    attachments:
    - color: danger
      fallback: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME <FAILURE>"
      text: "<!here> Build has failed"
      title: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME"
      title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

jobs:
- name: build
  public: true
  plan:
  - get: source
    trigger: true
  - task: maven
    timeout: 2h30m
    config:
      platform: linux
      image_resource:
        source: 
          repository:  harbor-repo.vmware.com/dockerhub-proxy-cache/springio/spring-ci-base
        type: docker-image
      inputs:
        - name: source
      caches:
        - path: source/.m2
        - path: source/.gradle
      run:
        dir: source
        path: sh
        args:
        - -c
        - |
          rm -rf ~/.m2 ~/.gradle
          ln -s $(pwd)/.m2 ~/.m2
          ln -s $(pwd)/.gradle ~/.gradle
          echo "((signing-key))" > private.asc
          gpg --import --batch --no-tty private.asc
          ./mvnw deploy -s .mvn/settings.xml
          GRADLE_PUBLISH_VERSION=$( sed '\!<parent!,\!</parent!d' pom.xml | grep '<version' | head -1 | sed -e 's/.*<version>//' -e 's!</version>.*$!!' )
          echo $GRADLE_PUBLISH_VERSION | grep -q SNAPSHOT
          if [ "$?" == "1" ]; then
            cd gradle-plugin/publish
            ./gradlew publishExisting
          fi
    params:
      TERM: -dumb
      passphrase: ((signing-passphrase))
      sonatype_username: ((sonatype-username))
      sonatype_password: ((sonatype-password))
      spring_username: ((artifactory-username))
      spring_password: ((artifactory-password))
      GRADLE_PUBLISH_KEY: ((gradle-publish-key))
      GRADLE_PUBLISH_SECRET: ((gradle-publish-secret))
    on_failure: *slack-failure
